using System;
using System.Collections.Generic;
//using Bogus;

namespace UploadTemplateGenerator.Models
{
    public class UploadData
    {
        public int RowID { get; set; }
        public string LeaseType { get; set; }
        public string OurRole { get; set; }
        public string ShorttermLease { get; set; }
        public string ImmaterialLease { get; set; }        
        public string ImmaterialComments { get; set; }
        public string OurAsset { get; set; }
        public string Classification { get; set; }
        public string LocalTransactionalCurrency { get; set; }
        public string FunctionalCurrency { get; set; }
        public string BuildingType { get; set; }
        public string BuildingUse { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string Address1 { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PossessionDate { get; set; }
        public string CurrentEndDate { get; set; }
        public string TerminateOption { get; set; }
        public string UsefulLife { get; set; }
        public string FairValue { get; set; }
        public string TitleTransferatLeaseEnd { get; set; }                    
        public string SalvageValue { get; set; }
        public string SpecializedUse { get; set; }
        public string EmailAlertRecipients { get; set; }
        public string VendorCompanyName { get; set; }
        public string BRAmount1 { get; set; }
        public string BREscalation1 { get; set; }
        public string BRFrequency1 { get; set; }
        public string BRFirstPaymentDate1 { get; set; }
        public string BRLastPaymentDate1 { get; set; }
        public string BRAmount2 { get; set; }
        public string BREscalation2 { get; set; }
        public string BRFrequency2 { get; set; }
        public string BRFirstPaymentDate2 { get; set; }
        public string BRLastPaymentDate2 { get; set; }
        public string BorrowingRate { get; set; }
        public string PropertyPlantandEquipment { get; set; }
        public string CAMAmount1 { get; set; }
        public string CAMEscalation1 { get; set; }
        public string CAMFrequency1 { get; set; }
        public string CAMFirstPaymentDate1 { get; set; }
        public string CAMLastPaymentDate1 { get; set; }
        public string ExpenditureCAM { get; set; }
        public string EliminationExpenditureCAM { get; set; }
        public string TaxAmount1 { get; set; }
        public string TaxEscalation1 { get; set; }
        public string TaxFrequency1 { get; set; }
        public string TaxFirstPaymentDate1 { get; set; }
        public string TaxLastPaymentDate1 { get; set; }
        public string ExpenditureTax { get; set; }
        public string EliminationExpenditureTax { get; set; }
        public string InsuranceAmount1 { get; set; }
        public string InsuranceEscalation1 { get; set; }
        public string InsuranceFrequency1 { get; set; }
        public string InsuranceFirstPaymentDate1 { get; set; }
        public string InsuranceLastPaymentDate1 { get; set; }
        public string ExpenditureInsurance { get; set; }
        public string EliminationExpenditureInsurance { get; set; }
        public string ExpenditureSalesTax { get; set; }
        public string EliminationExpenditureSalesTax { get; set; }
        public Dictionary<string, string> OtherPaymentExpenditure { get; set; }
        public Dictionary<string, string> OtherPaymentEliminationExpenditure { get; set; }
        public string Incentive { get; set; }
        public string IncentiveAmount { get; set; }
        public string IncentiveDescription { get; set; }
        public string IncentiveClearing { get; set; }
        public string InitialDirectCost { get; set; }
        public string InitialDirectCostAmount { get; set; }
        public string InitialDirectCostDescription { get; set; }
        public string InitialDirectCostClearing { get; set; }

        public string UnfavorableLeaseIntangibleLiability { get; set; }
        public string UnfavorableLeaseIntangibleLiabilityAmount { get; set; }
        public string UnfavorableLeaseIntangibleLiabilityDescription { get; set; }

        public string FavorableLeaseIntangibleAsset { get; set; }
        public string FavorableLeaseIntangibleAssetAmount { get; set; }
        public string FavorableLeaseIntangibleAssetDescription { get; set; }
        public string FundType { get; set; }
        public string ExpenditureAccount { get; set; }
        public string ExpenditureLeaseCapitalOutlayAccount { get; set; }
        public string ExpenditureLeasePrincipalAccount { get; set; }
        public string EliminationExpenditureAccount { get; set; }
        public string ExpenditureLeaseInterestAccount { get; set; }
        public string EliminationExpenditureLeaseCapitalOutlayAccount { get; set; }
        public string EliminationExpenditureLeasePrincipalAccount { get; set; }
        public string EliminationExpenditureLeaseInterestAccount { get; set; }
        public string OtherFinancingSourceLeaseAccount { get; set; }
        public string EliminationOtherFinancingSourceLeaseAccount { get; set; }
        public string ExpenditureTerminatedLeaseAccount { get; set; }
        public string ExpenditurePPECapitalOutlayAccount { get; set; }
        public string EliminationExpenditureTerminatedLeaseAccount { get; set; }
        public string EliminationExpenditurePPECapitalOutlayAccount { get; set; }
        public string AllocationBeneficiary1 { get; set; }
        public string AllocationPercentage1 { get; set; }

        //Update data
        public string LeaseID { get; set; }
        public string LeaseDescription { get; set; }
        public string ModelYear { get; set; }
        public string AssetCondition { get; set; }
        public string Address2 { get; set; }
        public string LeaseTitle { get; set; }
        public string AutomaticRenewalComment { get; set; }
        public string AutomaticRenewalDate { get; set; }
        public string AutomaticRenewalReoccurring { get; set; }
        public string AutomaticRenewalEndDate { get; set; }
        public string ContractionOptionComment { get; set; }
        public string ContractionOptionDate { get; set; }
        public string ContractionOptionReoccurring { get; set; }
        public string ContractionOptionEndDate { get; set; }
        public string ExpansionOptionComment { get; set; }
        public string ExpansionOptionDate { get; set; }
        public string ExpansionOptionReoccurring { get; set; }
        public string ExpansionOptionEndDate { get; set; }
        public string MaintenancebyLandlordComment { get; set; }
        public string MaintenancebyLandlordDate { get; set; }
        public string MaintenanceByLandlordReoccurring { get; set; }
        public string MaintenanceByLandlordEndDate { get; set; }
        public string MaintenancebyTenantComment { get; set; }
        public string MaintenancebyTenantDate { get; set; }
        public string MaintenancebyTenantReoccurring { get; set; }
        public string MaintenancebyTenantEndDate { get; set; }
        public string RoofComment { get; set; }
        public string RoofDate { get; set; }
        public string RoofReoccurring { get; set; }
        public string RoofEndDate { get; set; }
        public string HVACComment { get; set; }
        public string HVACDate { get; set; }
        public string HVACReoccurring { get; set; }
        public string HVACEndDate { get; set; }
        public string ParkingComment { get; set; }
        public string ParkingDate { get; set; }
        public string ParkingReoccurring { get; set; }
        public string ParkingEndDate { get; set; }
        public string PurchaseOption { get; set; }
        public string PurchaseAmount { get; set; }
        public string BargainPurchaseOption { get; set; }
        public string CertaintoPurchase { get; set; }
        public string PurchaseOptionComment { get; set; }
        public string PurchaseOptionDate { get; set; }
        public string PurchaseOptionReoccurring { get; set; }
        public string PurchaseOptionEndDate { get; set; }
        public string RelocationOptionComment { get; set; }
        public string RelocationOptionDate { get; set; }
        public string RelocationOptionReoccurring { get; set; }
        public string RelocationOptionEndDate { get; set; }
        public string RightofFirstOfferComment { get; set; }
        public string RightofFirstOfferDate { get; set; }
        public string RightofFirstOfferReoccurring { get; set; }
        public string RightofFirstOfferEndDate { get; set; }
        public string RightofFirstRefusalComment { get; set; }
        public string RightofFirstRefusalDate { get; set; }
        public string RightofFirstRefusalReoccurring { get; set; }
        public string RightofFirstRefusalEndDate { get; set; }
        public string TerminationOptionComment { get; set; }
        public string TerminationOptionDate { get; set; }
        public string TerminationOptionReoccurring { get; set; }
        public string TerminationOptionEndDate { get; set; }
        public string OtherComment { get; set; }
        public string OtherDate { get; set; }
        public string OtherReoccurring { get; set; }
        public string OtherEndDate { get; set; }
        public string VendorContact { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCountry { get; set; }
        public string VendorZipCode { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorCreditLine { get; set; }
        public string VendorPhone { get; set; }
        public string VendorFax { get; set; }
        public string VendorEmail { get; set; }
        public string VendorNumber { get; set; }
        public string VendorPaymentMethod { get; set; }
        public string IncentiveExpenseAccount { get; set; }
        public string IncentiveLiabilityAccount { get; set; }
        public string InitialDirectCostExpenseAccount { get; set; }
        public string InitialDirectCostAssetAccount { get; set; }
        public string FavorableLeaseExpenseAccount { get; set; }
        public string FavorableLeaseIntangibleAssetAccount { get; set; }
        public string UnfavorableLeaseExpenseAccount { get; set; }
        public string UnfavorableLeaseIntangibleLiabilityAccount { get; set; }
        public string GoodwillAccount { get; set; }
        public string RightofUseLeaseAssetAccount { get; set; }
        public string InterestRevenueAccount { get; set; }
        public string DeferredInflowofResourcesAccount { get; set; }
        public string STLeaseRecAccount { get; set; }
        public string LTLeaseRecAccount { get; set; }
        public string AccruedInterestLiabilityReceivableAccount { get; set; }
        public string LeaseRevenueAccount { get; set; }
        public string EquitytoNetPositionAccount { get; set; }
        public string BaseRentExpenseAccount { get; set; }
        public string STDeferredRentAccount { get; set; }
        public string LTDeferredRentAccount { get; set; }
        public string STPrepaidRentAccount { get; set; }
        public string LTPrepaidRentAccount { get; set; }
        public string STDeferredRevenueAccount { get; set; }
        public string LTDeferredRevenueAccount { get; set; }
        public string STRentReceivableAccount { get; set; }
        public string LTRentReceivableAccount { get; set; }
        public string InterestExpenseAccount { get; set; }
        public string AmortizationExpenseAccount { get; set; }
        public string STLeaseLiabAccount { get; set; }
        public string STLeaseLiabilityAccount { get; set; }
        public string LTLeaseLiabilityAccount { get; set; }
        public string AssetLeaseExpenseAccount { get; set; }
        public string AccountsReceivableAccount { get; set; }
        public string BeginningPrepaidRentAccount { get; set; }
        public string InitialDirectCostAccount { get; set; }
        public string LiabilityLeaseExpenseAccount { get; set; }
        public string GainLossOnForeignExchangeAccount { get; set; }
        public string GainLossOnLeaseTerminationAccount { get; set; }
        public string BeginningDeferredRentAccount { get; set; }
        public string CTAAccount { get; set; }
        public string EquityAccount { get; set; }
        public string ImpairmentLossAccount { get; set; }
        public string ImpairmentLiabilityPriorToTransitionAccount { get; set; }
        public string ROUAssetAccount { get; set; }
        public string LeaseExpenseAccount { get; set; }
        public string CashClearingAccount { get; set; }
        public string LTLeaseLiabAccount { get; set; }
        public string AccumulatedAmortizationAccount { get; set; }
        public string CapitalLeaseAssetAccount { get; set; }
        public string PropertyPlantandEquipmentPPEAccount { get; set; }
        public string CAMExpenseAccount { get; set; }
        public string TaxExpenseAccount { get; set; }
        public string InsuranceExpenseAccount { get; set; }
        public string SalesTaxExpenseAccount { get; set; }
        public string AccruedPercentageRentLiabilityAccount { get; set; }
        public string PercentageRentExpenseAccount { get; set; }
    }
}